config/routes.rb
Rails.application.routes.draw do

  root                'sessions#new'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :enrollments

  resources :sections

  resources :users

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
<div class="container">
  <small>
    Web Design and Development by <a href="http://www.avant-garded.com/">avant-gardED</a>.
  </small>
</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("ALU_logo1.png", alt: "ALU"), root_path %>
    </div>
<% if logged_in? %>
    <!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Courses</a></li>
        <li><a href="#">Groups</a></li>
        <li><a href="#">Resources</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Melvin Freeman<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">My Profile</a></li>
            <li><%= link_to "Account Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          </ul>
        </li>
      </ul>
    </div>
<% else %>
<% end %>
  </div><!-- /.container-fluid -->
</nav><! -- End nav -->

app/views/layouts/_loggedoutheader.html.erb
<header class="navbar navbar-default">
<div class="container">
    <div class="navbar-header">
    <%= link_to image_tag("ALU_logo1.png", alt: "ALU"), root_path %>
    </div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_userchartstyle.html.erb
    <style>

        #test .arc2 {
            stroke-weight:0.1;
            fill: #3660b0;
        }

        #outer {
            background:#FFFFFF;
            border-radius: 5px;
            color: #000;
        }

        #div1, #div2, #div3, #div4 {
            width: 33%;
            height: 200px;
            box-sizing: border-box;
            float: left;
        }

        #div2 .arc {
            stroke-weight: 0.1;
            fill: #f0a417;
        }

        #div2 .arc2 {
            stroke-weight: 0.1;
            fill: #b00d08;
        }

        #div3 .arc {
            stroke-weight: 0.1;
            fill: #1d871b;
        }


        .selectedRadial {
            border-radius: 3px;
            background: #f4f4f4;
            color: #000;
            box-shadow: 0 1px 5px rgba(0,0,0,0.4);
            -moz-box-shadow: 0 1px 5px rgba(0,0,0,0.4);
            border: 1px solid rgba(200,200,200,0.85);
        }

        .radial {
            border-radius: 3px;
            background: #FFFFFF;
            color: #000;

        }


    </style>

app/views/layouts/_userjavascript.html.erb
<script language="JavaScript">

    var div1=d3.select(document.getElementById('div1'));
    var div2=d3.select(document.getElementById('div2'));
    var div3=d3.select(document.getElementById('div3'));
    var div4=d3.select(document.getElementById('div4'));

    start();

    function onClick1() {
        deselect();
        div1.attr("class","selectedRadial");
    }

    function onClick2() {
        deselect();
        div2.attr("class","selectedRadial");
    }

    function onClick3() {
        deselect();
        div3.attr("class","selectedRadial");
    }

    function labelFunction(val,min,max) {

    }

    function deselect() {
        div1.attr("class","radial");
        div2.attr("class","radial");
        div3.attr("class","radial");
    }

    function start() {

        var rp1 = radialProgress(document.getElementById('div1'))
                .label("RADIAL 1")
                .onClick(onClick1)
                .diameter(150)
                .value(78)
                .render();

        var rp2 = radialProgress(document.getElementById('div2'))
                .label("RADIAL 2")
                .onClick(onClick2)
                .diameter(150)
                .value(132)
                .render();

        var rp3 = radialProgress(document.getElementById('div3'))
                .label("RADIAL 3")
                .onClick(onClick3)
                .diameter(150)
                .minValue(100)
                .maxValue(200)
                .value(150)
                .render();

    }





</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | ALU Learning Management</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <%= render 'layouts/userchartstyle' %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>